package com.example.entryrecording.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.entryrecording.bean.Entry;
import com.example.entryrecording.bean.Entrybase;
import com.example.entryrecording.bean.Sound;

import com.example.entryrecording.greendao.EntryDao;
import com.example.entryrecording.greendao.EntrybaseDao;
import com.example.entryrecording.greendao.SoundDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig entryDaoConfig;
    private final DaoConfig entrybaseDaoConfig;
    private final DaoConfig soundDaoConfig;

    private final EntryDao entryDao;
    private final EntrybaseDao entrybaseDao;
    private final SoundDao soundDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        entryDaoConfig = daoConfigMap.get(EntryDao.class).clone();
        entryDaoConfig.initIdentityScope(type);

        entrybaseDaoConfig = daoConfigMap.get(EntrybaseDao.class).clone();
        entrybaseDaoConfig.initIdentityScope(type);

        soundDaoConfig = daoConfigMap.get(SoundDao.class).clone();
        soundDaoConfig.initIdentityScope(type);

        entryDao = new EntryDao(entryDaoConfig, this);
        entrybaseDao = new EntrybaseDao(entrybaseDaoConfig, this);
        soundDao = new SoundDao(soundDaoConfig, this);

        registerDao(Entry.class, entryDao);
        registerDao(Entrybase.class, entrybaseDao);
        registerDao(Sound.class, soundDao);
    }
    
    public void clear() {
        entryDaoConfig.clearIdentityScope();
        entrybaseDaoConfig.clearIdentityScope();
        soundDaoConfig.clearIdentityScope();
    }

    public EntryDao getEntryDao() {
        return entryDao;
    }

    public EntrybaseDao getEntrybaseDao() {
        return entrybaseDao;
    }

    public SoundDao getSoundDao() {
        return soundDao;
    }

}
